sudo: required
services:
  - docker
env:
  global:
    - GIT_SHA:$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_f2999b9fd275_key -iv $encrypted_f2999b9fd275_iv -in multi-k8s-354418-525a44c3bb06.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-354418
  - gcloud config set compute/zone asia-southeast1-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME"
  - docker build -t trinhno/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true trinhno/react-test npm test
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
